// ===== Device Definitions =====
// 35+ devices with screen positioning data

const DEVICES = {
    // ===== iPhone =====
    iphone: [
        {
            id: 'iphone17promax',
            name: 'iPhone 17 Pro Max',
            icon: '📱',
            width: 440,
            height: 896,
            screenX: 20,
            screenY: 20,
            screenW: 400,
            screenH: 856,
            radius: 55,
            frameColor: '#1a1a1a',
            bezelWidth: 4,
            notch: { width: 130, height: 35 },
            dynamicIsland: true
        },
        {
            id: 'iphone17pro',
            name: 'iPhone 17 Pro',
            icon: '📱',
            width: 400,
            height: 820,
            screenX: 18,
            screenY: 18,
            screenW: 364,
            screenH: 784,
            radius: 50,
            frameColor: '#1a1a1a',
            bezelWidth: 4,
            dynamicIsland: true
        },
        {
            id: 'iphone17',
            name: 'iPhone 17',
            icon: '📱',
            width: 390,
            height: 800,
            screenX: 18,
            screenY: 18,
            screenW: 354,
            screenH: 764,
            radius: 48,
            frameColor: '#2a2a2a',
            bezelWidth: 4,
            dynamicIsland: true
        },
        {
            id: 'iphone16promax',
            name: 'iPhone 16 Pro Max',
            icon: '📱',
            width: 435,
            height: 890,
            screenX: 18,
            screenY: 18,
            screenW: 399,
            screenH: 854,
            radius: 54,
            frameColor: '#1a1a1a',
            bezelWidth: 4,
            dynamicIsland: true
        },
        {
            id: 'iphone16pro',
            name: 'iPhone 16 Pro',
            icon: '📱',
            width: 395,
            height: 815,
            screenX: 16,
            screenY: 16,
            screenW: 363,
            screenH: 783,
            radius: 50,
            frameColor: '#1a1a1a',
            bezelWidth: 4,
            dynamicIsland: true
        },
        {
            id: 'iphone16',
            name: 'iPhone 16',
            icon: '📱',
            width: 385,
            height: 790,
            screenX: 16,
            screenY: 16,
            screenW: 353,
            screenH: 758,
            radius: 46,
            frameColor: '#2a2a2a',
            bezelWidth: 4,
            dynamicIsland: true
        },
        {
            id: 'iphone15pro',
            name: 'iPhone 15 Pro',
            icon: '📱',
            width: 393,
            height: 808,
            screenX: 15,
            screenY: 15,
            screenW: 363,
            screenH: 778,
            radius: 48,
            frameColor: '#1c1c1c',
            bezelWidth: 4,
            dynamicIsland: true
        },
        {
            id: 'iphone15',
            name: 'iPhone 15',
            icon: '📱',
            width: 380,
            height: 780,
            screenX: 15,
            screenY: 15,
            screenW: 350,
            screenH: 750,
            radius: 45,
            frameColor: '#2d2d2d',
            bezelWidth: 4,
            dynamicIsland: true
        },
        {
            id: 'iphonese4',
            name: 'iPhone SE 4',
            icon: '📱',
            width: 370,
            height: 760,
            screenX: 14,
            screenY: 14,
            screenW: 342,
            screenH: 732,
            radius: 42,
            frameColor: '#3a3a3a',
            bezelWidth: 4,
            dynamicIsland: false
        },
        {
            id: 'iphone14',
            name: 'iPhone 14',
            icon: '📱',
            width: 375,
            height: 770,
            screenX: 14,
            screenY: 14,
            screenW: 347,
            screenH: 742,
            radius: 44,
            frameColor: '#2e2e2e',
            bezelWidth: 4,
            notch: { width: 120, height: 32 }
        }
    ],

    // ===== Samsung =====
    samsung: [
        {
            id: 'galaxys25ultra',
            name: 'Galaxy S25 Ultra',
            icon: '📱',
            width: 430,
            height: 920,
            screenX: 8,
            screenY: 8,
            screenW: 414,
            screenH: 904,
            radius: 12,
            frameColor: '#0f0f0f',
            bezelWidth: 3,
            punchHole: { x: 215, y: 35, r: 12 }
        },
        {
            id: 'galaxys25plus',
            name: 'Galaxy S25+',
            icon: '📱',
            width: 400,
            height: 870,
            screenX: 8,
            screenY: 8,
            screenW: 384,
            screenH: 854,
            radius: 12,
            frameColor: '#0f0f0f',
            bezelWidth: 3,
            punchHole: { x: 200, y: 35, r: 11 }
        },
        {
            id: 'galaxys25',
            name: 'Galaxy S25',
            icon: '📱',
            width: 370,
            height: 790,
            screenX: 8,
            screenY: 8,
            screenW: 354,
            screenH: 774,
            radius: 12,
            frameColor: '#1a1a1a',
            bezelWidth: 3,
            punchHole: { x: 185, y: 32, r: 10 }
        },
        {
            id: 'galaxys24ultra',
            name: 'Galaxy S24 Ultra',
            icon: '📱',
            width: 425,
            height: 910,
            screenX: 8,
            screenY: 8,
            screenW: 409,
            screenH: 894,
            radius: 10,
            frameColor: '#0a0a0a',
            bezelWidth: 3,
            punchHole: { x: 212, y: 34, r: 12 }
        },
        {
            id: 'galaxyzfold6',
            name: 'Galaxy Z Fold 6',
            icon: '📱',
            width: 550,
            height: 720,
            screenX: 12,
            screenY: 12,
            screenW: 526,
            screenH: 696,
            radius: 16,
            frameColor: '#1a1a1a',
            bezelWidth: 5,
            foldLine: true
        },
        {
            id: 'galaxyzflip6',
            name: 'Galaxy Z Flip 6',
            icon: '📱',
            width: 360,
            height: 780,
            screenX: 10,
            screenY: 10,
            screenW: 340,
            screenH: 760,
            radius: 24,
            frameColor: '#1e1e1e',
            bezelWidth: 4,
            foldLine: true
        },
        {
            id: 'galaxya55',
            name: 'Galaxy A55',
            icon: '📱',
            width: 365,
            height: 775,
            screenX: 10,
            screenY: 10,
            screenW: 345,
            screenH: 755,
            radius: 20,
            frameColor: '#2a2a2a',
            bezelWidth: 4,
            punchHole: { x: 182, y: 30, r: 10 }
        },
        {
            id: 'galaxytabs10',
            name: 'Galaxy Tab S10',
            icon: '📲',
            width: 800,
            height: 540,
            screenX: 20,
            screenY: 20,
            screenW: 760,
            screenH: 500,
            radius: 16,
            frameColor: '#1f1f1f',
            bezelWidth: 8
        }
    ],

    // ===== Android Other =====
    android: [
        {
            id: 'pixel9proxl',
            name: 'Pixel 9 Pro XL',
            icon: '📱',
            width: 410,
            height: 890,
            screenX: 12,
            screenY: 12,
            screenW: 386,
            screenH: 866,
            radius: 40,
            frameColor: '#1d1d1d',
            bezelWidth: 4,
            punchHole: { x: 205, y: 35, r: 12 }
        },
        {
            id: 'pixel9pro',
            name: 'Pixel 9 Pro',
            icon: '📱',
            width: 385,
            height: 830,
            screenX: 12,
            screenY: 12,
            screenW: 361,
            screenH: 806,
            radius: 38,
            frameColor: '#1d1d1d',
            bezelWidth: 4,
            punchHole: { x: 192, y: 32, r: 11 }
        },
        {
            id: 'pixel9',
            name: 'Pixel 9',
            icon: '📱',
            width: 375,
            height: 800,
            screenX: 12,
            screenY: 12,
            screenW: 351,
            screenH: 776,
            radius: 36,
            frameColor: '#252525',
            bezelWidth: 4,
            punchHole: { x: 187, y: 30, r: 10 }
        },
        {
            id: 'oneplus13',
            name: 'OnePlus 13',
            icon: '📱',
            width: 395,
            height: 870,
            screenX: 10,
            screenY: 10,
            screenW: 375,
            screenH: 850,
            radius: 42,
            frameColor: '#0d0d0d',
            bezelWidth: 4,
            punchHole: { x: 197, y: 32, r: 11 }
        },
        {
            id: 'xiaomi15ultra',
            name: 'Xiaomi 15 Ultra',
            icon: '📱',
            width: 405,
            height: 895,
            screenX: 8,
            screenY: 8,
            screenW: 389,
            screenH: 879,
            radius: 38,
            frameColor: '#111111',
            bezelWidth: 3,
            punchHole: { x: 202, y: 35, r: 12 }
        }
    ],

    // ===== iPad =====
    ipad: [
        {
            id: 'ipadpro13m4',
            name: 'iPad Pro 13" M4',
            icon: '📲',
            width: 860,
            height: 610,
            screenX: 25,
            screenY: 25,
            screenW: 810,
            screenH: 560,
            radius: 20,
            frameColor: '#1c1c1c',
            bezelWidth: 10
        },
        {
            id: 'ipadpro11m4',
            name: 'iPad Pro 11" M4',
            icon: '📲',
            width: 740,
            height: 520,
            screenX: 22,
            screenY: 22,
            screenW: 696,
            screenH: 476,
            radius: 18,
            frameColor: '#1c1c1c',
            bezelWidth: 8
        },
        {
            id: 'ipadair13',
            name: 'iPad Air 13"',
            icon: '📲',
            width: 850,
            height: 600,
            screenX: 28,
            screenY: 28,
            screenW: 794,
            screenH: 544,
            radius: 18,
            frameColor: '#2a2a2a',
            bezelWidth: 12
        },
        {
            id: 'ipadair11',
            name: 'iPad Air 11"',
            icon: '📲',
            width: 730,
            height: 510,
            screenX: 24,
            screenY: 24,
            screenW: 682,
            screenH: 462,
            radius: 16,
            frameColor: '#2a2a2a',
            bezelWidth: 10
        },
        {
            id: 'ipadmini7',
            name: 'iPad Mini 7',
            icon: '📲',
            width: 560,
            height: 400,
            screenX: 18,
            screenY: 18,
            screenW: 524,
            screenH: 364,
            radius: 14,
            frameColor: '#2d2d2d',
            bezelWidth: 8
        }
    ],

    // ===== MacBook =====
    macbook: [
        {
            id: 'macbookpro16m4',
            name: 'MacBook Pro 16" M4',
            icon: '💻',
            width: 1000,
            height: 640,
            screenX: 80,
            screenY: 25,
            screenW: 840,
            screenH: 525,
            radius: 12,
            frameColor: '#1e1e1e',
            bezelWidth: 12,
            hasNotch: true,
            keyboard: true
        },
        {
            id: 'macbookpro14m4',
            name: 'MacBook Pro 14" M4',
            icon: '💻',
            width: 900,
            height: 580,
            screenX: 72,
            screenY: 22,
            screenW: 756,
            screenH: 473,
            radius: 10,
            frameColor: '#1e1e1e',
            bezelWidth: 10,
            hasNotch: true,
            keyboard: true
        },
        {
            id: 'macbookair15m3',
            name: 'MacBook Air 15" M3',
            icon: '💻',
            width: 950,
            height: 610,
            screenX: 76,
            screenY: 24,
            screenW: 798,
            screenH: 499,
            radius: 10,
            frameColor: '#2d2d2d',
            bezelWidth: 10,
            hasNotch: true,
            keyboard: true
        },
        {
            id: 'macbookair13m3',
            name: 'MacBook Air 13" M3',
            icon: '💻',
            width: 850,
            height: 550,
            screenX: 68,
            screenY: 20,
            screenW: 714,
            screenH: 446,
            radius: 10,
            frameColor: '#2d2d2d',
            bezelWidth: 10,
            hasNotch: true,
            keyboard: true
        },
        {
            id: 'surfacelaptop6',
            name: 'Surface Laptop 6',
            icon: '💻',
            width: 920,
            height: 600,
            screenX: 70,
            screenY: 25,
            screenW: 780,
            screenH: 488,
            radius: 8,
            frameColor: '#3a3a3a',
            bezelWidth: 12,
            keyboard: true
        },
        {
            id: 'windowslaptop',
            name: 'Windows Laptop',
            icon: '💻',
            width: 900,
            height: 580,
            screenX: 70,
            screenY: 22,
            screenW: 760,
            screenH: 475,
            radius: 6,
            frameColor: '#2f2f2f',
            bezelWidth: 14,
            keyboard: true
        }
    ],

    // ===== Desktop =====
    desktop: [
        {
            id: 'imac24m4',
            name: 'iMac 24" M4',
            icon: '🖥️',
            width: 900,
            height: 720,
            screenX: 50,
            screenY: 40,
            screenW: 800,
            screenH: 500,
            radius: 24,
            frameColor: '#e5e5e7',
            bezelWidth: 20,
            chin: 60,
            stand: true
        },
        {
            id: 'studiodisplay',
            name: 'Studio Display',
            icon: '🖥️',
            width: 950,
            height: 720,
            screenX: 35,
            screenY: 30,
            screenW: 880,
            screenH: 550,
            radius: 16,
            frameColor: '#2d2d2d',
            bezelWidth: 15,
            stand: true
        },
        {
            id: 'dellultrasharp32',
            name: 'Dell UltraSharp 32"',
            icon: '🖥️',
            width: 1000,
            height: 680,
            screenX: 25,
            screenY: 20,
            screenW: 950,
            screenH: 560,
            radius: 8,
            frameColor: '#1a1a1a',
            bezelWidth: 10,
            stand: true
        },
        {
            id: 'lgultrawide34',
            name: 'LG UltraWide 34"',
            icon: '🖥️',
            width: 1100,
            height: 520,
            screenX: 30,
            screenY: 18,
            screenW: 1040,
            screenH: 430,
            radius: 6,
            frameColor: '#1f1f1f',
            bezelWidth: 12,
            stand: true
        },
        {
            id: 'gamingmonitor',
            name: 'Gaming Monitor',
            icon: '🖥️',
            width: 1000,
            height: 620,
            screenX: 20,
            screenY: 15,
            screenW: 960,
            screenH: 540,
            radius: 4,
            frameColor: '#0a0a0a',
            bezelWidth: 8,
            rgbGlow: true,
            stand: true
        }
    ],

    // ===== Watch =====
    watch: [
        {
            id: 'applewatchultra3',
            name: 'Apple Watch Ultra 3',
            icon: '⌚',
            width: 200,
            height: 240,
            screenX: 18,
            screenY: 32,
            screenW: 164,
            screenH: 176,
            radius: 40,
            frameColor: '#3a3a3a',
            bezelWidth: 8,
            crown: true
        },
        {
            id: 'applewatchs10',
            name: 'Apple Watch S10',
            icon: '⌚',
            width: 180,
            height: 220,
            screenX: 16,
            screenY: 28,
            screenW: 148,
            screenH: 164,
            radius: 38,
            frameColor: '#1c1c1c',
            bezelWidth: 6,
            crown: true
        },
        {
            id: 'galaxywatch7',
            name: 'Galaxy Watch 7',
            icon: '⌚',
            width: 190,
            height: 190,
            screenX: 20,
            screenY: 20,
            screenW: 150,
            screenH: 150,
            radius: 95,
            frameColor: '#2a2a2a',
            bezelWidth: 8,
            circular: true
        },
        {
            id: 'galaxywatchultra',
            name: 'Galaxy Watch Ultra',
            icon: '⌚',
            width: 210,
            height: 210,
            screenX: 22,
            screenY: 22,
            screenW: 166,
            screenH: 166,
            radius: 105,
            frameColor: '#3d3d3d',
            bezelWidth: 10,
            circular: true
        }
    ],

    // ===== Other =====
    other: [
        {
            id: 'smarttv65',
            name: 'Smart TV 65"',
            icon: '📺',
            width: 1100,
            height: 680,
            screenX: 20,
            screenY: 20,
            screenW: 1060,
            screenH: 596,
            radius: 8,
            frameColor: '#0d0d0d',
            bezelWidth: 12,
            stand: true
        },
        {
            id: 'smarttv55',
            name: 'Smart TV 55"',
            icon: '📺',
            width: 950,
            height: 590,
            screenX: 18,
            screenY: 18,
            screenW: 914,
            screenH: 514,
            radius: 6,
            frameColor: '#0f0f0f',
            bezelWidth: 10,
            stand: true
        },
        {
            id: 'ps5pro',
            name: 'PlayStation 5 Pro',
            icon: '🎮',
            width: 700,
            height: 450,
            screenX: 40,
            screenY: 30,
            screenW: 620,
            screenH: 349,
            radius: 16,
            frameColor: '#ffffff',
            bezelWidth: 25
        },
        {
            id: 'nintendoswitch2',
            name: 'Nintendo Switch 2',
            icon: '🎮',
            width: 600,
            height: 340,
            screenX: 100,
            screenY: 25,
            screenW: 400,
            screenH: 225,
            radius: 12,
            frameColor: '#1a1a1a',
            bezelWidth: 20,
            joycons: true
        }
    ]
};

// Get all devices as flat array
function getAllDevices() {
    return Object.values(DEVICES).flat();
}

// Get devices by category
function getDevicesByCategory(category) {
    if (category === 'all') return getAllDevices();
    return DEVICES[category] || [];
}
